imp: add specialArgs
gytis-ivaskevicius/flake-utils-plus pull request #26
Opened 2021-04-10 04:58 UTC by blaggacao

anything that is going to be passed to an `imports = []` necesarily
needs to be passed as specialArgs. This ensures it does not become
part of the module system (extraArgs = _module.args) itself.

Since it is not part of the module system, modules can evaluate based on
inputs, otherwise no fixed point would exists (infinit recursion).

This is a way to encapsulate profiles into bundles that are accessible
like so:

inputs = [ bundles.home ];

2021-04-10 05:01 UTC, Pacman99 requested changes
Outside of this it looks good

2021-04-10 05:01 UTC, Pacman99 commented on systemFlake.nix
> +    }: { inherit channelName system output builder modules specialArgs; };
```suggestion
    }: { inherit channelName system output builder modules extraArgs specialArgs; };
```

2021-04-10 05:15 UTC, Pacman99 approved these changes
I think this should be exposed, you can use it to set `modulesPath` or send groups of modules to a host, ex: mobile-nixos's flake needs to be used like this.

2021-04-12 18:13 UTC, gytis-ivaskevicius approved these changes
looks good to me :)

2021-04-12 18:23 UTC, merged